### ISSUE TITLE
error con la función getUser()  

### ISSUE THREAD

**Issue by rmonterrozag** [javebratt/ionic-angular-firebase-authentication-starter#10]
Hola Javier

Gracias por tu excelente trabajo. Soy un aficionado, estoy tratando de desarrollar el curso de Autenticación Firebase. 
En el uso de la función getUser() se genera un error que no he podido solucionar:

![getUser Error](https://user-images.githubusercontent.com/59850434/72303405-c6cfe700-3632-11ea-9d01-d088c3fd6969.png)

No se que hacer para solucionarlo, agradezco tu ayuda.

**Comment by javebratt** [comment]
Hmmm no sé que pueda ser, acá no me sale el error, que versión de Firebase y AngularFire tienes?

Yo estoy manejando:

```json
"dependencies": {
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/fire": "^5.3.0",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/core": "^5.19.1",
    "@ionic-native/splash-screen": "^5.19.1",
    "@ionic-native/status-bar": "^5.19.1",
    "@ionic/angular": "^4.11.8",
    "core-js": "^2.6.11",
    "firebase": "^6.6.2",
    "rxjs": "^6.5.4",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
```

**Comment by javebratt** [comment]
Hola, cierro esto por inactividad, si sigues teniendo el problema me cuentas
