### ISSUE TITLE
login-page.ts: Error with @ViewChild (requiring 2 parameters, just 1 delivered)

### ISSUE THREAD

**Issue by swissfritz** [javebratt/ionic-angular-firebase-authentication-starter#12]
I get this error:
<img width="431" alt="ViewChild" src="https://user-images.githubusercontent.com/15188594/74914235-a7c43200-53f4-11ea-8838-3be0d8630700.png">

**Comment by javebratt** [comment]
Hey there, it's because they were removed in Angular 9.

This project has been updated to

- @angular: "9.0.0"
- @angular/fire: "6..rc-1"
- @ionic/angular: "5.0.0"
- firebase: "7.8.1"

**Comment by swissfritz** [comment]
Thx Jorge, that solved it. Should have made sure to be on the newest releases.
