### ISSUE TITLE
licence?

### ISSUE THREAD

**Issue by rtpHarry** [javebratt/ionic-angular-firebase-authentication-starter#3]
Do you have a licence to go with this repo? At the moment it's not clear if it can be used in commercial projects.

**Comment by javebratt** [comment]
It can, I hadn't thought about it, give me a couple of hours and I'll see which is a flexible license and upload it. Any suggestions?

**Comment by rtpHarry** [comment]
Not sure, I just no it's a sticking point for open source adoption if there isn't any licence included so thought I would point it out.

**Comment by javebratt** [comment]
Done, I added the [MIT Licence](https://github.com/javebratt/ionic-angular-firebase-authentication-starter/blob/master/licence.md)
