### ISSUE TITLE
show error on profile page 

### ISSUE THREAD

**Issue by amnnzri** [javebratt/ionic-angular-firebase-authentication-starter#6]
1. i cant click 'name' on 'personal information' page 
2. For 'edit email' it show error 'ERROR: No document to update'
3. For my firebase console, i changed rules for database (which i dont know its correct or not)

Here's the image:

1. Issue i cant edit name and show this error on my developer tools
![Capture1](https://user-images.githubusercontent.com/43617013/66248839-20846380-e75e-11e9-8bcc-cb8f3ee41979.PNG)
### 
2. Issue i cant edit email and show this error on my developer tools 
![Capture3](https://user-images.githubusercontent.com/43617013/66248856-59bcd380-e75e-11e9-8852-f54be34bb2f3.PNG)
### 
3. My database rules for firebase (i dont know its correct or not )
![Capture2](https://user-images.githubusercontent.com/43617013/66248867-95f03400-e75e-11e9-9ee6-61c53e6230df.PNG)

**Comment by javebratt** [comment]
Did you check if the user profile is stored in the database?

There was an issue with Firestore + Auth communication a few weeks ago, where Firebase was not writing to the database to create the `userProfile` right after signup.

If there's no document in the database it can't update it.

**Comment by amnnzri** [comment]
so whats the actual database rule for firebase ? that one i only copy from another person issue

**Comment by javebratt** [comment]
Those rules should work, the issue wasn't in the rules, it was a defect affecting Firebase itself a while back. Did you check if the user profile is there in the database?

**Comment by amnnzri** [comment]
after user register, yes user profile show in database and can update 'User profile name'. Thank you so much
